# Generated by Django 4.0.5 on 2022-07-29 06:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itJob', '0002_user_is_firm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(choices=[('AAA', 'Python'), ('AAB', 'JavaScript'), ('AAC', 'Java'), ('AAD', 'C#'), ('AAE', 'Django'), ('AAF', 'C++'), ('AAG', 'Go'), ('AAH', 'Swift'), ('AAI', 'PHP'), ('AAJ', 'React')], max_length=3)),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='worker_skill',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itJob.worker'),
        ),
    ]
