# Generated by Django 4.0.5 on 2022-07-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itJob', '0004_worker_history_job_rename_work_firm_work_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker_history_job',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
