# Generated by Django 4.1 on 2022-08-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itJob', '0005_alter_worker_history_job_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker_skill',
            name='score',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AlterField(
            model_name='worker_skill',
            name='skill_name',
            field=models.CharField(max_length=64),
        ),
    ]
